cli:
  name: Test
  command: hexagon-test
  custom_tools_dir: .
tools:
  google:
    long_name: Google
    type: web
    action: open_link
    envs:
      "*": https://www.google.com/

  python-module:
    action: python-module
    type: shell
    alias: pm
    long_name: Python Module Test

  python-module-env:
    action: python-module-env
    type: shell
    alias: pme
    long_name: Python Module Env Test
    envs:
      "*":
        - 456
        - def

  node-module:
    action: node-module.js
    type: shell
    alias: nm
    long_name: Node Module Test

  node-module-env:
    action: node-module.js
    type: shell
    alias: nme
    long_name: Node Module Env Test
    envs:
      "*":
        - env_arg1
        - env_arg2
envs: {}
