name: guidelines

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - run: pip install flake8-bugbear
      - uses: TrueBrain/actions-flake8@v2
